server {
  listen $NGINX_PORT;
  server_name $NGINX_HOST;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /r2lb-proxy/ {
    proxy_pass http://192.168.1.30:8010/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
